---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections: 
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: docker run -d --name cockpit -p 8080:80 agentejo/
  mount_path: public
  working_dir: "/srv"
  instant_preview_command: docker build -t agentejo/cockpit:latest . --no-cache
